### ISSUE TITLE
x-terminal-editor is not available in all Distros/DEs

### ISSUE THREAD

**Issue by CPU-Blanc** [token2/fido2-manage#9]
Hello!

It would appear as though the gui.py is hardcoded to use `x-terminal-emulator` when setting/changing the PIN of the device, however, not all Linux distros/desktop environments have this available resulting in the following stacktrace

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "fido2-manage/gui.py", line 239, in change_pin
    subprocess.Popen(['x-terminal-emulator', '-e'] + command)
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'x-terminal-emulator'
```
Resulting in not being able to set it at all through the GUI and having to fallback to the command line.
In my case, I'm on Arch with Hyprland as my WM.

**Comment by token2** [comment]
What we mention in the main page "should work on any Linux distribution, but _we develop and test using Ubuntu_" refers to the command line part. We will check what can be done with the GUI part

**Comment by MBSck** [comment]
A quick fix for this would be just to check in what terminal emulator the script (I think we are speaking of the `gui.py` script?) is trying to execute and then set that as a variable.

For instance, I use `alacritty` and if I replace all the `x-terminal-emulator` with `alacritty` it works flawlessly.
So that would be a rather easy fix.

**Comment by token2** [comment]
> A quick fix for this would be just to check in what terminal emulator the script (I think we are speaking of the `gui.py` script?) is trying to execute and then set that as a variable.
> 
> For instance, I use `alacritty` and if I replace all the `x-terminal-emulator` with `alacritty` it works flawlessly. So that would be a rather easy fix.

This probably needs to be tested with a couple of different distros, but thanks for the hint

**Comment by token2** [comment]
> I had some time and made a pull-request [#20](https://github.com/token2/fido2-manage/pull/20) that should solve that problem (potentially for all distros).

Thanks a lot. The changes have been added. Will close the issue
